package GUI;

import data.Banco;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alber
 */
public class PAltasBajasModificaciones extends javax.swing.JPanel {

    /**
     * Creates new form PAltasBajasModificaciones
     */
    VPal v;
    Banco banco;
    public PAltasBajasModificaciones(VPal v, Banco banco) {
        this.v = v;
        this.banco = banco;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVacioArriba = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonAlta = new javax.swing.JButton();
        botonBaja = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        panelVacioAbajo = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(3, 1));

        panelVacioArriba.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRACIÓN DAMTANDER");
        panelVacioArriba.add(jLabel1);

        add(panelVacioArriba);

        botonAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonAlta.setText("Altas");
        botonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltaActionPerformed(evt);
            }
        });
        panelBotones.add(botonAlta);

        botonBaja.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonBaja.setText("Bajas");
        botonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajaActionPerformed(evt);
            }
        });
        panelBotones.add(botonBaja);

        botonModificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonModificar.setText("Modificaciones");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        panelBotones.add(botonModificar);

        botonVolver.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        panelBotones.add(botonVolver);

        add(panelBotones);

        javax.swing.GroupLayout panelVacioAbajoLayout = new javax.swing.GroupLayout(panelVacioAbajo);
        panelVacioAbajo.setLayout(panelVacioAbajoLayout);
        panelVacioAbajoLayout.setHorizontalGroup(
            panelVacioAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        panelVacioAbajoLayout.setVerticalGroup(
            panelVacioAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        add(panelVacioAbajo);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltaActionPerformed
    //lo mismo que en la tienda pero he quitado la opcion previa para elegir entre tipos de productos, o sea que mas sencillo
        try{
                String nombre = JOptionPane.showInputDialog("Introduce el nombre del prestamista");
                if (nombre == null || nombre.trim().isEmpty()) return; //si algun valor es null es que le ha dado a cancelar y se corta la alta
                String stringPorcentaje = JOptionPane.showInputDialog("Introduce el porcentaje de interes (25.4 por ejemplo)");
                if (stringPorcentaje == null) return;
                String stringNumPlazos = JOptionPane.showInputDialog("Introduce el plazo de meses del prestamo (34 por ejemplo)");
                if (stringNumPlazos == null) return;

                double porcentajeInteres = Double.parseDouble(stringPorcentaje);
                int numPlazos = Integer.parseInt(stringNumPlazos);

                boolean añadido = banco.añadirPrestamista(nombre, numPlazos, porcentajeInteres);
                if(añadido)
                    JOptionPane.showMessageDialog(null, "Prestamista añadido correctamente");
                else
                    JOptionPane.showMessageDialog(null, "No se ha podido añadir el prestamista");
                
    
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Formato de meses o porcentaje incorrectos, introduce numeros");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Error: " + ex.getMessage());
            Logger.getLogger(PAltasBajasModificaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        //de nuevo, para comprobar que ha cambiado la cantidad de prestamistas
        System.out.println("Prestamistas después de alta: " + banco.getPrestamistas().size());

    }//GEN-LAST:event_botonAltaActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        v.setContentPane(v.ppal);
        v.revalidate();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajaActionPerformed
        if(banco.getPrestamistas().isEmpty())
            JOptionPane.showMessageDialog(null, "No se puede eliminar nada, no hay prestamistas");
        else{
            //comparando nombres elimina uno si encuentra uno igual, si no nada.
            String prestamistaEliminado = JOptionPane.showInputDialog(banco.toString() + "\nIntroduce el nombre del prestamista a eliminar");
            if (prestamistaEliminado == null) return;
            boolean eliminado = banco.eliminarPrestamista(prestamistaEliminado);
            if(eliminado)
                JOptionPane.showMessageDialog(null, "Prestamista eliminado correctamente");
            else
                JOptionPane.showMessageDialog(null, "No se ha encontrado el prestamista o no existe.");
        }
    }//GEN-LAST:event_botonBajaActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        if(banco.getPrestamistas().isEmpty())
            JOptionPane.showMessageDialog(null, "No se puede modificar nada, no hay prestamistas en el banco");
        else{
            //tomamos valores y se intentan modificar en el nombre que hayamos puesto.
            try{
            String nombre = JOptionPane.showInputDialog(banco.toString() + "\nIntroduce el nombre del prestamista a modificar"); 
            if (nombre == null) return;
            String stringPorcentaje = JOptionPane.showInputDialog("Introduce el nuevo porcentaje de interes"); 
            if (stringPorcentaje == null) return;
            String stringPlazos = JOptionPane.showInputDialog("Introduce el nuevo numero de meses de plazo del prestamo"); 
            if (stringPlazos == null) return;

            double nuevoPorcentaje = Double.parseDouble(stringPorcentaje);
            int nuevoPlazos = Integer.parseInt(stringPlazos);

            boolean modificado = banco.modificarPlazosPorcentajesPrestamista(nombre, nuevoPorcentaje, nuevoPlazos);
            if(modificado)
                JOptionPane.showMessageDialog(null, "Prestamista modificado correctamente");
            else
                JOptionPane.showMessageDialog(null, "Error, no se ha encontrado el prestamista o no existe");
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, "Error al modificar: " + e.getMessage());
        }   catch (Exception ex) {
                Logger.getLogger(PAltasBajasModificaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            
        }
        
    }//GEN-LAST:event_botonModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlta;
    private javax.swing.JButton botonBaja;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelVacioAbajo;
    private javax.swing.JPanel panelVacioArriba;
    // End of variables declaration//GEN-END:variables
}
