package GUI;

import data.Banco;
import data.Prestamista;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alber
 */
public class PListados extends javax.swing.JPanel {

    /**
     * Creates new form PListados
     */
    Banco banco;
    VPal v;
    public PListados(VPal v, Banco banco) {
        this.v = v;
        this.banco = banco;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaListado = new javax.swing.JTextArea();
        panelInferior = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        botonListadoNormal = new javax.swing.JButton();
        botonListadoConsolas = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.GridLayout(2, 1));

        areaListado.setColumns(20);
        areaListado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaListado.setRows(5);
        jScrollPane1.setViewportView(areaListado);

        add(jScrollPane1);

        panelInferior.setLayout(new java.awt.GridLayout(2, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelInferior.add(jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelInferior.add(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panelInferior.add(jPanel5);

        botonListadoNormal.setText("Listado de prestamistas");
        botonListadoNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoNormalActionPerformed(evt);
            }
        });
        panelInferior.add(botonListadoNormal);

        botonListadoConsolas.setText("Simulador de prestamo");
        botonListadoConsolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoConsolasActionPerformed(evt);
            }
        });
        panelInferior.add(botonListadoConsolas);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        panelInferior.add(botonVolver);

        add(panelInferior);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.areaListado.setText("");
        v.setContentPane(v.ppal);
        v.revalidate();

    }//GEN-LAST:event_botonVolverActionPerformed
    //listado normal de todos los productos
    private void botonListadoNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoNormalActionPerformed
        this.areaListado.setText(banco.toString());
    }//GEN-LAST:event_botonListadoNormalActionPerformed

    private void botonListadoConsolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoConsolasActionPerformed
        try {
            this.areaListado.setText(listarPrestamistasConDinero("Estos son los prestamos que te podemos ofrecer \n"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            Logger.getLogger(PListados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonListadoConsolasActionPerformed
    
    private String listarPrestamistasConDinero(String titulo) throws Exception{
        String stringDinero = JOptionPane.showInputDialog(null, "Introduce la cantidad de dinero que deseas pedir");
        if(stringDinero == null)
            throw new Exception("Necesitamos una cantidad de dinero para simular el prestamo");
        int dinero = Integer.parseInt(stringDinero);
        if(dinero < 1000 || dinero > 300000){
            throw new Exception("No se pueden pedir creditos de menos de 1000 euros o de mas de 300000 euros");
        }
        StringBuilder resultado = new StringBuilder(titulo);
        for (Prestamista p : banco.getPrestamistas()) {
            double pagoConInteres = dinero * (1 +(p.getPorcentajeInteres() / 100));
            double pagoPlazo = pagoConInteres / p.getNumPlazos();
            resultado.append(p.toString())
                .append(String.format(" | Total a pagar del préstamo con intereses: %.2f", pagoConInteres))
                .append(String.format("€ | Dinero a pagar en un plazo: %.2f", pagoPlazo))
                .append(" €\n");
        }
        return resultado.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaListado;
    private javax.swing.JButton botonListadoConsolas;
    private javax.swing.JButton botonListadoNormal;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInferior;
    // End of variables declaration//GEN-END:variables
}
