package GUI;

import data.Banco;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author alber
 */
public class VPal extends javax.swing.JFrame {
    
    public Banco banco;
    JPanel ppal,pABM,pListados;
    final String NOM;
    
    public VPal(String nom, Banco tienda) {
        this.banco = tienda;
        this.NOM=nom;
        this.setTitle(NOM);
        //le paso la ventana y el banco a los paneles para que pueda usarlo facilmente
        ppal = new PPal(this.banco,this);
        pABM = new PAltasBajasModificaciones(this,this.banco);
        pListados = new PListados(this,this.banco);
        
        initComponents();
        this.setSize(1300,900);
        this.setLocationRelativeTo(null);
        this.setContentPane(ppal);
        /*para evitarme lios con los guardados he decidido cambiar la operación de cierre
        para que cuando cierres la app con la X guarde también los datos*/
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                tienda.guardarPrestamistasEnArchivo("res/prestamistas.txt");
                JOptionPane.showMessageDialog(null, "Datos guardados. Hasta la próxima!");
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
